### ISSUE TITLE
conductivity reconstruction using CR EPT

### ISSUE THREAD

**Issue by Jiayue2000** [EPTlib/eptlib#4]
When I tried to reconstruct the conductivity image using CR-EPT, I noticed that the reconstruction time varied greatly. Sometimes it completed in just a few seconds, while at other times it took over an hour. I suspect this may be related to the parameters I set. Currently, I am reconstructing human brain images with a resolution of [0.6, 0.6, 1.31]. My parameter settings are as follows: bc_sigma=0.01, ad_coeff=0.05, sg_degree=2, sg_size=[2,2,2], and step=[2e-3, 2e-3, 2e-3].

I found that the reconstruction speed is very slow, and the overall conductivity values are quite low. I am unsure whether this is related to the parameter settings or to my B1 phase itself. I noticed that the B1 phase values are mostly positive, which differs significantly from the simulated data. I am uncertain whether this discrepancy might affect the final results.

![output](https://github.com/user-attachments/assets/a7956b4d-85af-47a0-b438-e4a24b1b7cfd)

**Comment by alessandroarduino** [comment]
Unfortunately, there is no way to control directly the reconstruction time of CR-EPT. However, you can manipulate it implicitly by changing the CR-EPT parameters

```toml
[parameter]
    max-iterations = 1000
    tolerance = 1e-6
```

Precisely, you can experience a speed-up by reducing the number of iterations (parameter max-iterations) and/or increasing the tolerance.

The other parameters that you wrote seem reasonable to me. Also the map of the transceive phase seems OK (the phase is defined up to a constant, so it does not matter if it has negative values or not).
You can try to increase a bit the boundary condition (bc_sigma) and to decrease the artificial diffusion (ad_coeff), looking for an optimum. If you have not done it yet, give a look also at Helmholtz-EPT. It should give you the correct range of conductivity values in the image, which you can use to correct the boundary condition.

**Comment by Jiayue2000** [comment]
Thank you for your response and assistance. It has been very helpful to me. I would like to ask further: if I obtain the conductivity range using Helmholtz-EPT, how can I use this range to correct the boundary condition?

**Comment by alessandroarduino** [comment]
You are performing brain imaging. The electrical conductivity of white matter (the tissue with the largest volume) should be around 0.3 S/m (the exact value depends on the Larmor frequency and, to a certain extent, to the subject). If you see that the Helmholtz-EPT reconstruction agrees with this value, you can use it as a boundary condition for CR-EPT, through the parameter

```toml
[parameter.dirichlet]
    electric-conductivity = 0.3
```

**Comment by Jiayue2000** [comment]
Understood, thank you very much!
